version: "3.7"
services:
  database:
    image: mysql:5.7
    container_name: database
    environment: 
      MYSQL_ROOT_PASSWORD: 123456Pl
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: Clarusway_1
    networks:
      - bookstore-web
  my-app:
    image: bookstore-api:latest
    container_name: my-app
    restart: always
    depends_on:
      - database
    networks:
      - bookstore-web
    ports:
      - "80:80"
networks:
  bookstore-web:
    driver: bridge